# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fa3c26d7-e911-48d0-81e0-9c43c9628f74";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/fa3c26d7-e911-48d0-81e0-9c43c9628f74";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/log" =
    { device = "/dev/disk/by-uuid/fa3c26d7-e911-48d0-81e0-9c43c9628f74";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/cache" =
    { device = "/dev/disk/by-uuid/fa3c26d7-e911-48d0-81e0-9c43c9628f74";
      fsType = "btrfs";
      options = [ "subvol=@cache" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/fa3c26d7-e911-48d0-81e0-9c43c9628f74";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/fa3c26d7-e911-48d0-81e0-9c43c9628f74";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/995D-2E3C";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
